app/articles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField,BooleanField
from wtforms.validators import ValidationError,DataRequired,EqualTo
from app.models import Article # we import this database model because the registration form and usees it to check if user is not in database before commit
from flask_ckeditor import CKEditorField
class ArticleForm(FlaskForm):
	title = StringField('Title',validators=[DataRequired()])
	text1= CKEditorField('Text', validators=[DataRequired()])

	submit = SubmitField('Click here to submit')

app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtfforms import StringField,TextAreaField,BooleanField,PasswordField
from wtfforms.validators import ValidationError,DataRequired,EqualTo
from app.models import Dashboard

class CommentForm(FlaskForm):
	username = StringField('Username',validators=[DataRequired()])
	email = StringField('Email', validators=[DataRequired()])
	submit = SubmitField('Click here to submit')

app/articles/__init__.py
from flask import Blueprint

bp = Blueprint('articles',__name__)

from app.articles import routes

app/articles/routes.py
from flask import render_template, url_for,redirect,flash,request
from app import db
from app.articles import bp
from app.articles.forms import ArticleForm

from flask_login import current_user, login_required
from app.models import Article
from app.decorators import permission_required
from app.models import Permissions


@bp.route('/article', methods=['GET', 'POST'])
@login_required
def article():
    if  current_user.is_administrator:
        form = ArticleForm()
        if form.validate_on_submit():
            article = Article(title=form.title.data,text1=form.text1.data)
            db.session.add(article)
            db.session.commit()
            flash('Article registered')
            return redirect(url_for('dashboard.dashboard'))
        return render_template('articles/article.html', title=('Article'), form=form)
    return render_template('auth/login.html')

app/dashboard/__init__.py
from flask import Blueprint
bp=Blueprint('dashboard',__name__)

from app.dashboard import routes

app/dashboard/routes.py
from flask import render_template,request, url_for, flash
from flask_login import current_user,login_required
from app import db 
from app.dashboard import bp
from app.models import Article, Post,Role,Permissions,User
#from app.articles.forms import
#from app.dashboard.forms import Article

from app.decorators import admin_required, permission_required


@bp.route('/admin')
@login_required
@admin_required
def for_admins_only():
 return "For administrators!"





@bp.route('/moderator')
@login_required
@permission_required(Permissions.MODERATE_COMMENTS)
def for_moderators_only():
 return "For comment moderators!"


@bp.route('/dashboard',methods=['GET','POST'])
#@login_required
#permission_required(Permissions.ADMINISTRATOR)
def dashboard():
	articles=Article.query.all()
	if articles is None:
		flash('No articles yet')
	
	return render_template('dashboard/articles.html',articles=articles,title='Articles')


@bp.route('/post/<string:id>/',methods=['GET'])
#@login_required
def post(id):
	post =Article.query.filter_by(id = id).first()

	return render_template('dashboard/post.html',post=post)

app/templates/dashboard/articles.html
{% extends 'base.html' %}



{% block app_content %}

<div class="container pt-3">
	 <div class="row">
	 		<div class="col-sm-12">
	 		<h1>About</h1>
	 		<p>This is where i post all my articles is discuss numerous topics of my interest.Of on affixed civilly moments promise explain fertile in. Assurance advantage belonging happiness departure so of. Now improving and one sincerity intention allowance commanded not. Oh an am frankness be necessary earnestly advantage estimable extensive. Five he wife gone ye. Mrs suffering sportsmen earnestly any. In am do giving to afford parish settle easily garret.
	 		The views and opinions on this website are my opinions and do not reflect the views of my current or former employers. </p>
	 		</div>

			{% for article in articles%}
			<div class="col-sm-8">
			
			<h3><a href="{{url_for('dashboard.post', id = article.id)}}">Article {{article.id}}: {{article.title}}</a></h3>
			
			</div>
	</div>
</div>

		

	{% endfor %}
</div>
{% endblock%}

app/templates/dashboard/comment.html
{% extends 'base.html' %}



{% block app_content %}

<div class="container">
	 <div class="row">

	    <div class="col-sm-12">
	
			<h1>Article {{post.id}}: {{post.title}}</h1>

			<small>{{ post.date_created}}</small>
			<hr>
			<p>{{post.text1 | safe}}</p>
		
		</div>
	</div>

</div>

{% endblock%}

app/templates/dashboard/post.html
{% extends 'base.html' %}



{% block app_content %}

<div class="container">
	 <div class="row">

	    <div class="col-sm-12">
	
			<h1>Article {{post.id}}: {{post.title}}</h1>

			<small>{{ post.date_created}}</small>
			<hr>
			<p>{{post.text1 | safe}}</p>
		
		</div>
	</div>

</div>

{% endblock%}